### ISSUE TITLE
Black circle on the floor

### ISSUE THREAD

**Issue by ToMathh** [AcChosen/VR-Stage-Lighting#17]
I've noticed that when you look away from the light a black circle appears, I've changed many settings and haven't found a way to make it disappear, a bug or lack of expertise on my part ?

And of course, congratulations on your remarkable work !
Thanks for your time !

(a screen is attached)
![Capture d'écran 2023-06-03 010200](https://github.com/AcChosen/VR-Stage-Lighting/assets/68101798/38af325b-9e2e-4d39-a359-a8f968d0b348)

**Comment by AcChosen** [comment]
![image](https://github.com/AcChosen/VR-Stage-Lighting/assets/49845629/6b568639-6f29-400e-a6dd-74791e5d8b3d)

So what's happening is that end of the projection cone mesh is either too close or too far away from the camera, causing those triangles at the cap of the cone to not render. This usually happens if you have your light very very far away from the ground for example. So what you can do is increase or decrease this parameter. You may have to edit the shader to increase its maximum range by editing the last number in the parenthesis at the end. (I'll increase this range in the next update soon!)

![image](https://github.com/AcChosen/VR-Stage-Lighting/assets/49845629/4ec53f34-5677-4144-8f76-5636b91fef12)

**Comment by ToMathh** [comment]
Thank you very much for your quick reply, it has indeed corrected my problem !
Have a great week and congratulations again for your work on VRSL !
